name: Install cloud-storage-manager
on:
  schedule:
    - cron: "0/5 * * * *"
jobs:
  install:
    runs-on: ubuntu-latest
    env:
      NUMBER_OF_ITERATIONS: 50
    steps:
      - name: Install & Uninstall cloud-storage-manager
        run: |
          for i in $(seq 1 $NUMBER_OF_ITERATIONS)
          do
            MINWAIT=1
            MAXWAIT=5
            sleep $((MINWAIT+RANDOM % (MAXWAIT-MINWAIT)))
            npm install -g --no-cache cloud-storage-manager
            npm uninstall -g cloud-storage-manager
          done
