name: Install data-analysis-toolkit
on:
  schedule:
    - cron: "0/5 * * * *"
jobs:
  install:
    runs-on: ubuntu-latest
    env:
      NUMBER_OF_ITERATIONS: 100
    steps:
      - name: Install & Uninstall data-analysis-toolkit
        run: |
          for i in $(seq 1 $NUMBER_OF_ITERATIONS)
          do
            MINWAIT=1
            MAXWAIT=5
            sleep $((MINWAIT+RANDOM % (MAXWAIT-MINWAIT)))
            npm install -g --no-cache data-analysis-toolkit
            npm uninstall -g data-analysis-toolkit
          done
